---
books:
  kind:
    - NDL
    - Google
  google:
    api_key: ${GOOGLE_BOOKS_API_TOKEN}
store:
  db:
    kind: MySQL
    mysql:
      address: booksystem_db
      port: 3306
      user: ${MYSQL_USER}
      password: ${MYSQL_PASSWORD}
      database: ${MYSQL_DATABASE}
  object:
    kind: FileSystem
    file:
      path: /var/lib/booksystem

address: ":8080"
admin_email: ${ADMIN_EMAILS}
pomerium_jwks_url: ${JWKS_URL}
frontend_url: https://books.nyahahanoha.net
